# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-08 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u5e74\u5ea6\u8003\u6838\u5956')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u57fa\u5c42\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('holiday', models.CharField(max_length=20, verbose_name='\u8282\u65e5')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u8282\u65e5\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u5e94\u53d1\u91d1\u989d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='NonStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u5e74\u91d1')),
                ('medical', models.FloatField(default=0.0, verbose_name='\u4e2a\u4eba\u7edf\u7b79\u533b\u7597')),
                ('old', models.FloatField(default=0.0, verbose_name='\u517b\u8001\u8865\u5dee')),
                ('house_p', models.FloatField(default=0.0, verbose_name='\u4f4f\u623f\u516c\u79ef\u91d1\uff08\u4e2a\u4eba\uff09')),
                ('house_o', models.FloatField(default=0.0, verbose_name='\u4f4f\u623f\u516c\u79ef\u91d1\uff08\u5355\u4f4d\uff09')),
                ('house_fix', models.FloatField(default=0.0, verbose_name='\u623f\u6539\u4f4f\u623f\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceAppraisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('tax', models.FloatField(default=0.0, verbose_name='\u6240\u5f97\u7a0e')),
                ('award', models.FloatField(default=0.0, verbose_name='2.5\u500d\u8003\u6838\u5956')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u5b9e\u53d1\u5408\u8ba1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u517b\u8001\u4fdd\u9669\u4e34\u65f6\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='SingleChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u5e94\u53d1\u91d1\u989d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='TackHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary', models.FloatField(default=0.0, verbose_name='\u5e94\u652f\u4ed8\u672a\u4f11\u5e74\u4f11\u5047\u5de5\u8d44\u62a5\u916c')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('salary_card', models.IntegerField(verbose_name='\u5de5\u8d44\u5361\u53f7')),
                ('salary_job', models.FloatField(default=0.0, verbose_name='\u804c\u52a1\u5de5\u8d44')),
                ('salary_lv', models.FloatField(default=0.0, verbose_name='\u7ea7\u522b\u5de5\u8d44')),
                ('salary_sp', models.FloatField(default=0.0, verbose_name='\u7279\u533a\u6d25\u8d34')),
                ('salary_bc', models.FloatField(default=0.0, verbose_name='\u57fa\u7840\u6d25\u8d34')),
                ('salary_year_p', models.FloatField(default=0.0, verbose_name='\u804c\u4e1a\u5e74\u91d1\u4e2a\u4eba')),
                ('salary_year_o', models.FloatField(default=0.0, verbose_name='\u804c\u4e1a\u5e74\u91d1\u5355\u4f4d')),
                ('salary_year', models.FloatField(default=0.0, verbose_name='\u5e74\u91d1')),
                ('salary_assess', models.FloatField(default=0.0, verbose_name='\u5956\u52b1\u6027\u7ee9\u6548\u5de5\u8d44')),
                ('salary_t', models.FloatField(default=0.0, verbose_name='\u5e94\u53d1\u5de5\u8d44')),
                ('sp_salary', models.FloatField(default=0.0, verbose_name='\u4e2a\u4eba\u7f34\u7eb3\u793e\u4fdd\u8d39-\u4e2a\u4eba\u5408\u8ba1')),
                ('sp_medical', models.FloatField(default=0.0, verbose_name='\u4e2a\u4eba\u7f34\u7eb3\u793e\u4fdd\u8d39-\u4e2a\u4eba\u533b\u7597')),
                ('sp_old', models.FloatField(default=0.0, verbose_name='\u4e2a\u4eba\u7f34\u7eb3\u793e\u4fdd\u8d39-\u4e2a\u4eba\u517b\u8001')),
                ('sp_medical_count', models.FloatField(default=0.0, verbose_name='\u4e2a\u4eba\u7f34\u7eb3\u793e\u4fdd\u8d39-\u4e2a\u4eba\u7edf\u7b79\u533b\u7597')),
                ('tax', models.FloatField(default=0.0, verbose_name='\u6240\u5f97\u7a0e')),
                ('accumulation_p', models.FloatField(default=0.0, verbose_name='\u4e2a\u4eba\u516c\u79ef\u91d1')),
                ('accumulation_o', models.FloatField(default=0.0, verbose_name='\u5355\u4f4d\u516c\u79ef\u91d1')),
                ('salary_r', models.FloatField(default=0.0, verbose_name='\u5b9e\u53d1\u5de5\u8d44')),
                ('house_fix', models.FloatField(default=0.0, verbose_name='\u623f\u6539\u8865\u8d34')),
                ('so_salary', models.FloatField(default=0.0, verbose_name='\u5355\u4f4d\u7f34\u7eb3\u793e\u4fdd\u8d39-\u5355\u4f4d\u793e\u4fdd\u5408\u8ba1')),
                ('so_medical', models.FloatField(default=0.0, verbose_name='\u5355\u4f4d\u7f34\u7eb3\u793e\u4fdd\u8d39-\u5355\u4f4d\u533b\u7597')),
                ('so_old', models.FloatField(default=0.0, verbose_name='\u5355\u4f4d\u7f34\u7eb3\u793e\u4fdd\u8d39-\u5355\u4f4d\u517b\u8001')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
    ]
