# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-30 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadreDutyAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('standard', models.FloatField(verbose_name='\u6807\u51c6')),
                ('subsidy', models.FloatField(verbose_name='\u8865\u8d34')),
                ('index', models.FloatField(verbose_name='\u6570\u91cf')),
                ('tax', models.FloatField(verbose_name='\u6240\u5f97\u7a0e')),
                ('other', models.FloatField(verbose_name='\u5176\u5b83\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('standard', models.FloatField(verbose_name='\u6807\u51c6')),
                ('amount', models.FloatField(verbose_name='\u91d1\u989d')),
                ('index', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('tax', models.FloatField(verbose_name='\u6240\u5f97\u7a0e')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='GovPerformanceAppraisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('standard', models.FloatField(verbose_name='\u6807\u51c6')),
                ('amount', models.FloatField(verbose_name='\u91d1\u989d')),
                ('ratio', models.FloatField(verbose_name='\u7cfb\u6570')),
                ('tax', models.FloatField(verbose_name='\u6240\u5f97\u7a0e')),
                ('other', models.FloatField(verbose_name='\u6263\u9664\u5176\u5b83')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='PreYearEndPerformanceAppraisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('standard', models.FloatField(verbose_name='\u6807\u51c6')),
                ('index', models.FloatField(verbose_name='\u6570\u91cf')),
                ('tax', models.FloatField(verbose_name='\u6240\u5f97\u7a0e')),
                ('other', models.FloatField(verbose_name='\u5176\u5b83\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='ReallySalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('post_wage', models.FloatField(verbose_name='\u5c97\u4f4d\u5de5\u8d44')),
                ('level_wage', models.FloatField(verbose_name='\u85aa\u7ea7\u5de5\u8d44')),
                ('area_allowance', models.FloatField(verbose_name='\u7279\u533a\u6d25\u8d34')),
                ('base_allowance', models.FloatField(verbose_name='\u57fa\u7840\u6d25\u8d34')),
                ('special_post_allowance', models.FloatField(verbose_name='\u7279\u6b8a\u5c97\u4f4d\u6d25\u8d34')),
                ('shortage_post', models.FloatField(verbose_name='\u7d27\u7f3a\u5c97\u4f4d')),
                ('nursing_age', models.IntegerField(verbose_name='\u62a4\u9f84')),
                ('urance_benefit', models.FloatField(verbose_name='\u4fdd\u9669\u91d1')),
                ('housing_fund', models.FloatField(verbose_name='\u4f4f\u623f\u516c\u79ef\u91d1')),
                ('housing_fund2', models.FloatField(verbose_name='\u4f4f\u623f\u516c\u79ef\u91d12')),
                ('tax', models.FloatField(verbose_name='\u6240\u5f97\u7a0e')),
                ('rent', models.FloatField(verbose_name='\u623f\u79df')),
                ('utilities', models.FloatField(verbose_name='\u6c34\u7535')),
                ('other', models.FloatField(verbose_name='\u5176\u5b83')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialBenefitAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('standard', models.FloatField(verbose_name='\u6807\u51c6')),
                ('index', models.FloatField(verbose_name='\u6570\u91cf')),
                ('tax', models.FloatField(verbose_name='\u6240\u5f97\u7a0e')),
                ('other', models.FloatField(verbose_name='\u5176\u5b83\u8865\u8d34')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
