# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-29 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assess',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='nonstaff',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='performanceappraisa',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='provide',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='singlechild',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='tackholiday',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
        migrations.AlterField(
            model_name='total',
            name='user',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237'),
        ),
    ]
