# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_auto_20170430_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadredutyaward',
            name='title',
            field=models.CharField(default='\u5e72\u90e8\u804c\u52a1\u5956\u52b1\u6027\u7ee9\u6548', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.CharField(default='\u9662\u966a\u4f19\u98df\u8865', max_length=100),
        ),
        migrations.AddField(
            model_name='govperformanceappraisa',
            name='title',
            field=models.CharField(default='\u653f\u5e9c\u7ee9\u6548\u8003\u6838\u5956', max_length=100),
        ),
        migrations.AddField(
            model_name='preyearendperformanceappraisa',
            name='title',
            field=models.CharField(default='\u9884\u53d1\u5e74\u7ec8\u7ee9\u6548\u5de5\u8d44', max_length=100),
        ),
        migrations.AddField(
            model_name='reallysalary',
            name='title',
            field=models.CharField(default='\u7f16\u5185\u6b63\u5f0f\u5de5\u5de5\u8d44', max_length=100),
        ),
        migrations.AddField(
            model_name='specialbenefitaward',
            name='title',
            field=models.CharField(default='\u7279\u522b\u6548\u76ca\u5956\u52b1\u6027\u7ee9\u6548', max_length=100),
        ),
    ]
